Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Petspot.Models;
using Petspot.Services;
using System.Diagnostics;

namespace Petspot.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;

        public HomeController(IHomeService homeService)
        {
            _homeService = homeService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Search(string Owner)
        {
            return View(_homeService.Search(Owner));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OwnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Petspot.Models;
using Petspot.Services;

namespace Petspot.Controllers
{
    [Authorize]
    public class OwnerController : Controller
    {
        private readonly IOwnerService _ownerService;

        public OwnerController(IOwnerService ownerService)
        {
            _ownerService = ownerService;
        }

        // GET: Owner/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            var owner = await _ownerService.Details(id);
            if (owner == null)
            {
                return NotFound();
            }
            return View(owner);
        }

        // GET: Owner/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Owner/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Owner owner)
        {
            var result = await _ownerService.Create(owner);
            if (result == null)
            {
                return StatusCode(StatusCodes.Status409Conflict);
            }
            return RedirectToAction("Create", "Pet");
        }

        // GET: Owner/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            var result = await _ownerService.EditGet(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        // POST: Owner/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, Owner owner)
        {
            var result = await _ownerService.EditPost(id, owner);
            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction("Details", new { id = id });
        }

        // GET: Owner/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            var result = await _ownerService.DeleteGet(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        //POST: Owner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var result = await _ownerService.DeletePost(id);
            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Petspot.Models;
using Petspot.Services;

namespace Petspot.Controllers
{
    [Authorize]
    public class PetController : Controller
    {
        private readonly IPetService _petService;

        public PetController(IPetService petService)
        {
            _petService = petService;
        }

        // GET: Pet/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            var result = await _petService.Details(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        // GET: Pet/Create
        public IActionResult Create()
        {
            DataList(null);
            return View();
        }

        // POST: Pet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pet pet)
        {
            await _petService.Create(pet);
            return RedirectToAction("Index", "Home");
        }

        // GET: Pet/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            var result = await _petService.EditGet(id);
            if (result == null)
            {
                return NotFound();
            }

            DataList(result);
            return View(result);
        }

        // POST: Pet/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, Pet pet)
        {
            var result = await _petService.EditPost(id, pet);
            if (result == null)
            {
                return View(pet);
            }
            return RedirectToAction("Details", new { id = id });
        }

        // GET: Pet/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            var result = await _petService.DeleteGet(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        // POST: Pet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            var result = await _petService.DeletePost(id);
            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction("Index", "Home");
        }

        private object DataList(Pet? pet)
        {
            var owners = _petService.Owners();
            if (pet == null)
            {
                return ViewData["OwnerId"] = new SelectList(owners, "Id", "Name");
            }
            return ViewData["OwnerId"] = new SelectList(owners, "Id", "Name", pet.OwnerId);
        }
    }
}

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Petspot.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row g-5 align-items-center">
        <div class="col-lg-6 text-center text-lg-start">
            
            @if (SignInManager.IsSignedIn(User))
            {
                <h1 class="text-black mb-4">Welcome, 
                    <a class="text-capitalize text-decoration-none text-black">
                        @UserManager.Users.FirstOrDefault(name => name.Email == UserManager.GetUserName(User)).FirstName
                    </a>
                </h1>
            }
            else
            {
                <h1 class="text-black mb-4">We really care about your pet's well-being!</h1>
            }

            <p class="text-black pb-3">Our mission is to give veterinarians a website where can register the pets and owners.
                                        This project has done for the final paper of Academy .Net</p>
            @if (SignInManager.IsSignedIn(User))
            {
                <a role="button" class="btn btn-primary rounded-pill" asp-controller="Pet" asp-action="Create">Register Pet</a>
                <a role="button" class="btn btn-primary rounded-pill" asp-controller="Owner" asp-action="Create">Register Owner</a>
            }     
        </div>
        <div class="col-lg-6 text-center text-lg-start">
            <img class="img-fluid mt-5" src="https://www.kindnessoftulsa.com/wp-content/uploads/2018/01/Layer-23.png" alt="">
        </div>
    </div>
</div>

Views/Home/Search.cshtml
@model List<Owner>
@using Microsoft.AspNetCore.Identity
@using Petspot.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Owners";
}
<h2 class="text-center mb-5 border-bottom">@ViewData["Title"]</h2>

@if (Model != null && Model.Any())
{
    <div class="row">
        @foreach (Owner owner in Model)
        {
            <div class="col-sm-4">
                <div class="card border-info bg-info bg-opacity-10 mb-4">
                    <div class="card-body">
                        @if (owner.Pets.Count() > 0)
                        {
                            if (owner.Pets.FirstOrDefault(pet => pet.ImageName != "") != null)
                            {
                                <img src="@("~/images/dbImages/" + owner.Pets.First(pet => pet.ImageName != null).ImageName)" asp-append-version="true" class="rounded-circle card-img float-start ms-0 border border-info" alt="Pet's Photo" style="width: 150px; height: 125px;" />
                            }
                        }
                        <h5 class="card-title d-inline me-1"><a class="text-decoration-none text-black" href="~/owner/details/@owner.Id">@owner.Name</a></h5>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a asp-controller="Owner" asp-action="Edit" asp-route-id="@owner.Id"><i class="bi bi-pen-fill"></i></a>
                            <a asp-controller="Owner" asp-action="Delete" asp-route-id="@owner.Id"><i class="bi bi-person-x-fill"></i></a>
                        }
                        <div class="d-flex flex-column mt-1">
                            @foreach (Pet pet in owner.Pets)
                            {
                                <div class="d-flex flex-row mb-1">
                                    <a href="~/pet/details/@pet.Id" class="ms-1 text-decoration-none me-auto px-2">@pet.Name</a>
                                    @if (SignInManager.IsSignedIn(User)) 
                                    {
                                        <div>
                                            <a class="card-text" asp-controller="Pet" asp-action="Edit" asp-route-id="@pet.Id"><i class="bi bi-pencil-fill"></i></a>
                                            <a class="card-text" asp-controller="Pet" asp-action="Delete" asp-route-id="@pet.Id"><i class="bi bi-trash3-fill"></i></a>
                                        </div>
                                    }
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <img src="~/images/404Error.png" class="rounded mx-auto d-block h-50 w-50">
}